### ISSUE TITLE
Unable to send you a payment

### ISSUE THREAD

**Issue by Kiwwa** [evilbuck/trello-list-filter#6]
Sorry for posting this as a Github issue, but I followed the "how to send support" link on your Chrome Plugin page and was unable to send it through.

In either case, love the plugin 🙌

![image](https://user-images.githubusercontent.com/3986174/62989960-77239e80-be8d-11e9-88a9-4433de8c5c26.png)

**Comment by evilbuck** [comment]
Thanks! I'm really bad about checking this repo. The messages come in waves. It's a side project, and this last year was really busy (as I'm sure it affected all of us).

**Comment by Kiwwa** [comment]
No worries - I'll leave this open for you to close whenever you'd like 👍
